# Generated by Django 4.2.6 on 2023-10-31 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_user_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', to='blog.friendship'),
        ),
        migrations.AlterField(
            model_name='user',
            name='requests',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', to='blog.friendrequest'),
        ),
    ]
