# Generated by Django 4.2.6 on 2023-11-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_user_friends_alter_user_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferable_cars',
            field=models.ManyToManyField(to='blog.category'),
        ),
    ]
